- name: create lxc container
  proxmox:
        api_user: client@pam
        api_token_id: awx_client
        api_token_secret: "{{ prox_api }}""
        api_host: "{{ prox_ip }}"
        node: proxmoxtest
        hostname: "{{ prox_name }}"
        ostemplate: 'local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz'
        storage: local-lvm
        state: present 
        netif: '{"net0":"name=etho,ip={{ vm_ip }}/24,bridge=vmbr0,gw=192.168.56.1"}'

- name: wait for
  wait_for:
     timeout: 5
  delegate_to: localhost

- name: start vm
  proxmox:
        api_user: client@pam
        api_token_id: awx_client
        api_token_secret: "{{ prox_api }}"
        api_host: "{{ prox_ip }}"
        node: "{{ prox_name }}"
        hostname: "{{ vm_name }}"
        state: started